INSERT INTO book_genre
VALUES (0, 'UNIDENTIFIED'),
       (1, 'SPECULATIVE'),
       (2, 'REALIST'),
       (3, 'ADVENTURE'),
       (4, 'COMING_OF_AGE'),
       (5, 'CRIME'),
       (6, 'FANTASY'),
       (7, 'MILITARY'),
       (8, 'PARANORMAL'),
       (9, 'ROMANCE'),
       (10, 'SCIENCE_FICTION'),
       (11, 'SUPERNATURAL'),
       (12, 'WESTERN'),
       (13, 'HORROR'),
       (14, 'HISTORICAL'),
       (15, 'ENCYCLOPEDIC'),
       (16, 'ACADEMIC'),
       (17, 'HISTORY'),
       (18, 'PHILOSOPHY'),
       (19, 'COMEDY'),
       (20, 'ESSAY'),
       (21, 'JOURNALISM'),
       (22, 'NATURE');